### ISSUE TITLE
Add `:after` content

### ISSUE THREAD

**Issue by tomhodgins** [LukyVj/covfefe.css#2]
Hey @LukyVj, interesting use of CSS, but I couldn't help but notice your CSS file (and JS snippet) could be condensed to:

```javascript
document.body.innerHTML+=`<style>:before,:after{content:'covfefe'!important`
```

Which would double the covfefe of the plugin.

I hope you understand.

**Comment by LukyVj** [comment]
Hey @tomhodgins 
Thanks for that, of course, there is never enough covfefe! 

I will add this in the day 😂

Thanks!
